services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - PUID=1000
      - PGID=1000
    volumes:
      - evolution_mongodb_data:/data/db
      - evolution_mongodb_configdb:/data/configdb
    mem_limit: 1.5g
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    expose:
      - 27017
    networks:
      - coolify

  redis:
    container_name: redis
    image: redis:7.2.12
    restart: unless-stopped
    ports:
      - 6380:6379
    command: >
      redis-server
      --appendonly yes
      -- maxmemory 256mb
      -- maxmemory-policy allkeys-lru
    volumes:
      - evolution_redis:/data
    mem_limit: 256m
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "-p", "6379", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - coolify

  evolution-api:
    container_name: evolution_api-prod
    image: atendai/evolution-api:v1.8.0
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - SERVER_URL=${SERVER_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - CORS_METHODS=${CORS_METHODS}
      - CORS_CREDENTIALS=${CORS_CREDENTIALS}
      - CONFIG_SESSION_PHONE_CLIENT=${CONFIG_SESSION_PHONE_CLIENT}
      - CONFIG_SESSION_PHONE_NAME=${CONFIG_SESSION_PHONE_NAME}
      - QRCODE_LIMIT=${QRCODE_LIMIT}
      - AUTHENTICATION_TYPE=${AUTHENTICATION_TYPE}
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
      - STORE_MESSAGES=true
      - STORE_MESSAGE_UP=true
      - STORE_CONTACTS=true
      - STORE_CHATS=true
      - CLEAN_STORE_CLEANING_INTERVAL=7200
      - CLEAN_STORE_MESSAGES=true
      - CLEAN_STORE_MESSAGE_UP=true
      - CLEAN_STORE_CONTACTS=true
      - CLEAN_STORE_CHATS=true
      - DATABASE_ENABLED=true
      - DATABASE_CONNECTION_URI=mongodb://admin:password@mongodb:27017/?authSource=admin&readPreference=primary&ssl=false&directConnection=true
      - DATABASE_CONNECTION_DB_PREFIX_NAME=evo
      - DATABASE_SAVE_DATA_CONTACTS=true
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379
      - CACHE_REDIS_PREFIX_KEY=evolution
      - CACHE_REDIS_TTL=604800
      - CONFIG_SESSION_PHONE_VERSION=${BAILEYS_VERSION}
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8081:8080"
    mem_limit: 1g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    networks:
      - coolify

  next-app:
    container_name: next-app-prod
    build:
      context: ./
      dockerfile: ./app/prod.Dockerfile
      args:
        - NODE_ENV=production
        - ASAAS_LINK_PAGAMENTO_UNICO=${ASAAS_LINK_PAGAMENTO_UNICO}
        - ASAAS_LINK_PAGAMENTO_RECORRENTE=${ASAAS_LINK_PAGAMENTO_RECORRENTE}
        - EVOLUTION_API_URL=${EVOLUTION_API_URL}
        - DATABASE_URL=${DATABASE_URL}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - AUTH_SECRET=${AUTH_SECRET}
        - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
        - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
        - AUTH_URL=${AUTH_URL}
        - AUTH_REDIRECT_PROXY_URL=${AUTH_REDIRECT_PROXY_URL}
        - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
        - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    restart: unless-stopped
    environment:
      NODE_OPTIONS: --max-old-space-size=512
    volumes:
      - nextjs_cache:/app/.next
      - .:/app
      - prisma_volume:/app/node_modules/@prisma
    ports:
      - 3000:3000
    depends_on:
      evolution-api:
        condition: service_healthy
    mem_limit: 768m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - coolify

volumes:
  nextjs_cache:
  evolution_store:
  evolution_instances:
  evolution_redis:
  prisma_volume:
  evolution_mongodb_data:
  evolution_mongodb_configdb: